version: '3.8'

services:
  mongodb:
    image: mongo:7.0.2
    container_name: nest-i18n-mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
